"""
Manages the persistence of AI conversation history.

This module provides the `ConversationManager` class, which is responsible for
storing, retrieving, and updating chat conversations in the application's
database. This allows the AI to have "memory" across multiple interactions
within the same conversation thread.
"""
import logging
import uuid
import json
from typing import List, Dict, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

class ConversationManager:
    """
    Handles database operations for storing and retrieving conversation history.

    This class abstracts the logic for interacting with the `conversations`
    table. It ensures that conversation turns are saved correctly and can be
    retrieved to provide context for future AI responses.

    Attributes:
        db: An active database connection object.
    """
    
    def __init__(self, db_connection):
        """
        Initializes the ConversationManager with a database connection.

        Args:
            db_connection: A sqlite3 connection object to the application database.
        """
        self.db = db_connection
        self._ensure_table_exists()

    def _ensure_table_exists(self):
        """Create the conversations table if it doesn't exist."""
        try:
            self.db.execute("""
                CREATE TABLE IF NOT EXISTS conversations (
                    id TEXT PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    last_updated_at TEXT NOT NULL,
                    history TEXT NOT NULL,
                    summary TEXT
                );
            """)
            self.db.commit()
        except Exception as e:
            logger.error(f"Failed to create conversations table: {e}")

    def get_history(self, user_id: int, conversation_id: Optional[str]) -> List[Dict]:
        """
        Retrieves the message history for a specific conversation.

        If the conversation_id is not provided or not found, it returns an
        empty list, signifying the start of a new conversation.

        Args:
            user_id: The ID of the user requesting the history.
            conversation_id: The unique identifier for the conversation.

        Returns:
            A list of dictionaries, where each dictionary is a "turn" in the
            conversation, or an empty list if no history is found.
        """
        if not conversation_id:
            return []
            
        try:
            cursor = self.db.cursor()
            cursor.execute("SELECT history FROM conversations WHERE id = ? AND user_id = ?", (conversation_id, user_id))
            row = cursor.fetchone()
            return json.loads(row[0]) if row else []
        except Exception as e:
            logger.error(f"Failed to get conversation history: {e}")
            return []

    def save_turn(self, user_id: int, conversation_id: Optional[str], user_message: str, assistant_message: str, context: Dict) -> str:
        """
        Saves a user message and assistant response as a single "turn".

        If `conversation_id` is None, a new conversation record is created in
        the database. Otherwise, the existing conversation's history is
        updated with the new turn.

        Args:
            user_id: The ID of the user who initiated the turn.
            conversation_id: The existing conversation ID, or None to create a new one.
            user_message: The message sent by the user.
            assistant_message: The full response generated by the AI.
            context: The context dictionary used for generating the response (for potential future analysis).

        Returns:
            The unique ID of the conversation that was updated or created.
        """
        timestamp = datetime.now().isoformat()
        turn = {"user_message": user_message, "assistant_message": assistant_message, "timestamp": timestamp}
        
        try:
            history = self.get_history(user_id, conversation_id)
            history.append(turn)
            history_json = json.dumps(history)

            if not conversation_id:
                conversation_id = str(uuid.uuid4())
                self.db.execute("INSERT INTO conversations (id, user_id, created_at, last_updated_at, history) VALUES (?, ?, ?, ?, ?)",
                                (conversation_id, user_id, timestamp, timestamp, history_json))
            else:
                self.db.execute("UPDATE conversations SET history = ?, last_updated_at = ? WHERE id = ?",
                                (history_json, timestamp, conversation_id))
            self.db.commit()
            return conversation_id
        except Exception as e:
            logger.error(f"Failed to save conversation turn: {e}")
            return conversation_id # Return original ID even if save fails